# Generated by Django 3.2.25 on 2025-11-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_salary', models.FloatField()),
                ('emp_mobile', models.BigIntegerField()),
                ('emp_dept', models.CharField(max_length=50)),
                ('emp_join_date', models.DateField()),
            ],
        ),
    ]
